EJERCICIO CONJUNTO_NUMEROS ES
AMBIENTE
NODO=REGISTRO
	DATO: NUMERICO (4)
	POSICION: NUMERICO (2)
	PROX:PUNTERO A NODO
FIN REGISTRO
PROCEDIMIENTO CARGA_NUMEROS() ES 
	ESC("POR FAVOR INGRESE UN CONJUNTO DE NUMEROS, ELLOS ESTARAN SEPARADOS POR (0), PARA TERMINAR LA CARGA INGRESE UN NEGATICO")
	LEER(RESPUESTA)
	MIENTRAS RESPUESTA>0 HACER
		NUEVO(P)
		P.DATO:=RESPUESTA
		P.POSICION:=P.POSICION+1
		P.PROX:=NIL
		SI PRIM=NIL ENRONCES
			PRIM:=P
		SINO 
			A.PROX:=P
		FS
		A:=P
		ESC("INGRESE EL SIGUIENTE")
		LEER(RESPUESTA)
	FM
FP 

PROCEDIMIENTO MIN() ES
	SI P.DATO < MIN_SUBCONJUNTO ENTONCES
		MIN_SUBCONJUNTO:=P.DATO
	FSI
FP

PROCEDIMIENTO MAX() ES 
	SI P.DATO > MAX_CONJUNTO ENTONCES
		MAX_CONJUNTO := P.DATO
		RES_POSCION:=P.POSICION
		RES_SUNCPNJUNTO:=SUBCONJUNTO
	FS
FP
				
PROCESO

RES_POSCION:=1
MAX_CONJUNTO:=LV ; MIN_SUBCONJUNTO:=HV
PROMEDIO:=0
SUBCONJUNTO:=0
DIV:=0

PRIM:=NIL
 CARGA_NUMEROS()
P:=PRIM
 SI P=NIL ENTONCES
	ESC("NO SE ENCONTRARON NUMEROS CARGADOS")
 MIENTRAS P<>NIL HACER
	MIENTRAS P.DATO>0 HACER
		PROMEDIO:=PROMEDIO+P.DATO
		DIV:=P.POSICION
		MAX(); MIN()
		P:=P.PROX
	FM 
	SUBCONJUNTOS:=SUBCONJUNTOS+1
	SI PROMEDIO>0 ENTONCES //PORQUE SI NO HAY NADA ENTONCES HAY CEROS CONSECUTIVOS
		ESC("PORMEDIO DEL SUBCONJUNTO NUMERO ", SUBCONJUNTO, "ES DE" PROMEDIO/DIV)
		ESC("EL MINIMOS ENCONTRADO EN ESTE CONJUNTO ES "MIN_SUBCONJUNTO)
	SINO
		ESC("ERROR, SE HAYO CEROS CONSECUTIVOS EN ESTA SECCION")
		SUBCONJUNTO:=SUBCONJUNTO-1 //NO CUENTO A CONJUNTOS DE CEROS COMO UN CONJUNTO EN SI, POR ESO LE RESTO UNO
		SI SUBCONJUNTO<0 ENTONCES
			SUBCONJUNTO:=0
	FIN SI
	PROMEDIO:=0
	MIN_SUBCONJUNTO:=0
 FM
 SI SUBCONJUNTOS>0 ENTONCES
	ESC("VALOR MAXIMO DEL CONJUNTO ES ", MAX_CONJUNTO,"SE ENCUENTRA EN", RES_SUNCPNJUNTO, "EN LA POSICION", RES_POSCION)
	ESC("TOTAL DE SUBCONJUNTOS PROCESADOS", SUBCONJUNTOS)
 FS
FP







EJERCICO 2
AMBIENTE
TIPO_REG=REGISTRO  //SOLO DEL GANADOR 
	PUNTOS:
	GOLPESTOT:
FR 

HEROES: ARREGLO DE {1..11}, {1..10} DE TIPO_REG

FUNCION HEORE(AN(15)):NUMERICO(2) ES
	:"BATMAN"::=1
	...
	:"IRONMAN"::=10
FF

PROCEDIMIENTO CARGAR_MATRIZ() ES
MIENTRAS NFDA(REG) HACER
	i:=HEROE(REG.SUPERHEROE)
	j:=HEROE(REG.SUPERHEROE2)
	PUN1:=(REG.GOLPES_PARCIALES1/2)+REG.GOLPESTOTALES1
	PUN2:=(REG.GOLPES_PARCIALES2/2)+REG.GOLPESTOTALES2
	SI PUN1>PUN2 ENTONCES
		HEROES[i,j].PUNTOS:=PUN1
		HEROES[i,j].GOLPESTOT:=REG.GOLPESTOTOTALES1
	SINO
		HEROES[i,j].PUNTOS:=PUN2
		HEROES[i,j].GOLPESTOT:=REG.GOLPESTOTALES2
	FS
	
	PUN1:=0; PUN2;=0

	HEROE[11, i].PUNTOS:=HEROES[i,j].PUNTOS
	HEROES[i,j].GOLPESTOT:=REG.GOLPESTOTALES1  //ACA DISCRIMINO EN SI PERDIO O GANO, EL TOTAL DE LA LINEA 11
	HEROE[11, j].PUNTOS:=HEROES[i,j].PUNTOS 
	HEROES[i,j].GOLPESTOT:=REG.GOLPESTOTALES2  //MUESTRA UN TOTAL GENERAL, NO SOLO TOTAL DE PELEAS Q GANARON
	R(ARCH, REG)
FP
PROCESO
CARGAR_MATRIZ()
PARA j=1 A 10 HACER
	SI HEROES[11, J].PUNTOS<PUNTOS_MENOR ENTONCES
		PUNTOS_MENOR:= HEROES[11, J].PUNTOS
		RES_HEROE:=j
	FS
	SI HEROE[11, j].PUNTOS>LIDER_PUNTOS ENTONCES
		LIDER:=j
		LIDER_PUNTOS:=HEROE[11, j].PUNTOS
	FS
	SI HEROES[11, J].GOLPES < 10 ENTONCES
		ESC("EL SUPERHEROE NRO" J, "RECIBIO MENOS DE 10 GOLPES TOTALES")
	FS
FS
PARA i:=1 A 10 HACER
	SI HEROES[i, LIDER].PUNTOS>vencido_PUNTOS ENTONCES
		vencido_PUNTOS:=HEROES[i, LIDER].PUNTOS
		RES_VENCIDO:=i
	FS
FP
W("HEROE LIDER", LIDER, "VENCIO CON MAS PUNTOS A ", RES_VENCIDO)
FP