ACCION EJERCICIO1 ES
AMBIENTE
import CONCATENAR()
//Se entiende que una sola cosa que se elija
// EJEMPLO SEC: 1234|JOSEMANUEL-|10|1|L
INDEX=REGISTRO
	HC:ENTERO(4)
	DIA={'L','M','V'}
FIN REGISTRO
ARCH: archivo indexado por HC
r:INDEX
CLINICA: secuencia de caracteres
c:caracter
USER:string
OP: {1, 2 , 3}
ESPECIALIDAD:ARRAY [1..20]
COBERTURA: ARRAY [1..10]

PROCEDIMIENTO minimo() ES


FUNCION ANUM(X:caracter):entero ES
	SEGUN X HACER
		:'0':=0
		:'1':=1
		..ETC
	FIN SEGUN
FIN FUN

FUNCION ARNUM(K:entero):entero ES
	PARA i:=K hasta 1 HACER
		num:=num + ANUM(c)*(10**i)
		AVZ(CLINICA,c)
	FIN PARA
FIN FUNCION

PROCEDIMIENTO CPARAR() ES
	ABRIR /S(ARCH)
	ARR(CLINICA); AVZ(CLINICA, c)
	MIENTRAS NOFDS(CLINICA) HACER
		r.HC:=ARNUM(4)
		GRABAR(ARCH, R)
		REPETIR
			AVZ(CLINICA, c)
		HASTA QUE c = '-'
		PARA J:=1 HASTA 3 HACER
			AVZ(CLINICA, c)
		FINPARA
		r.DIA:=c
		GRABAR(ARCH, R)
		AVZ(CLINICA, c)
	FIN MIENTRAS
	W("ARCHIVO INDEZADO POR HISTORIA CLINICA CREADA CON EXITO")
	CERRAR(ARCH)
	CERRAR(CLINICA)
FINPROCE

PROCEDIMIENTO BUSCAR() ES
AMBIENTE
	ENCONTRADO: boolean
PROCESO
	ENCONTRADO:= false
	W("por favor, ingrese usuario a encontrar")
	R(USER)
	ARR(CLINICA); AVZ(CLINICA, c)
	PARA j:=1 a 4 HACER
		AVZ(CLINICA, c)
	FIN PARA
	MIENTRAS NOFDS(CLINICA) Y NOENCONTRADO HACER
		MIENTRAS c<>'-' HACER
			ÑAM:=CONCATENAR(ÑAM,c)
			AVZ(CLINICA)
		FIN MIENTRAS
		SI USER=ÑAM ENTONCES
			AVZ(CLINICA)
			W("ESPECIALIDAD DEL PACIENTE:")
			W(c)
			AVZ(CLINICA, c)
			W(c)
			AVZ(CLINICA, c)
			AVZ(CLINICA, c)
			W("DIA DE LA SEMANA QUE SE ATENDIO", c)
			ENCONTRADO:=true
		SINO//NO SE PONER A CERO UN STRING
			ÑAM:=nil
			PARA j:=1 a 5 HACER
				AVZ(CLINICA,c)
			FIN PARA
		FIN SI
	FIN  MIENTRAS
	SI NOENCONTRADO ENTONCES 
		W("NO SE ENCONTRO COINCIDENCIA")
	FIN SI
	CERRAR(CLINICA)
FIN PROCESO
//1234|JOSEGUSTAVOMANUEL-|10|1|L
PROCEDIMIENTO INFORMAR() ES
	//PONER A CERO LOS ARREGLOS ETCE
	ARR(CLINICA); AVZ(CLINICA, c)
	MIENTRAS NOFDS(CLINICA) HACER
		REPETIR 
			AVZ(CLINICA, c)
		HASTA QUE c='-'
		AUXILIAR:=ARNUM(2)
		ESPECIALIDAD[(AUXILIAR-10)]:=ESPECIALIDAD[(AUXILIAR-10)] + 1
		AVZ(CLINICA, c)
		COBERTURA[ANUM(c)+1]:=COBERTURA[ANUM(c)+1] + 1
		PARA i:=1 A 5 HACER
			AVZ(CLINICA, c)
		FIN PARA
	FIN MIENTRAS	
	W("TOTAL POR ESPECIALIDAD")	
	PARA M:=1 A 19 HACER
		W("ESPECIALIDAD", M, " TIENE UN TOTAL DE", ESPECIALIDAD[M])
	FIN PARA
	W("ESPECIALIDAD MAS ATENDIDA ES ", ESPECIALIDADMAX)
	W("TOTAL POR COBERTURA")
	PARA N:=1 A 10 HACER	
		W("COBERTURA ", N, " TIENE UN TOTAL DE", COBERTURA[N])
	FIN PARA
	W("COBERTURA MENOS ATENDIDA ES", COBERTURAMIN)	
CERRAR(CLINICA)
	//me dio paja hacer las funciones de minimo y maximo, mañana hago
PROCESO
W("ingrese una opcion")
R(OP)
SEGUN OP HACER
	:1:= CPARAR()
	:2:= BUSCAR()
	:3:= INFORMAR()
	:OTRO:= w("opcion invalida")
FIN SEGUN
FIN ALGORITMO
 

//en total me llevo 1 hora 10 sin funciones de min y max
