ACCION FINAL2024 ES

DPTOS= REGISTRO
	NRODEPTO:N(6)
	DECRIPCION:AN(200)
	ESTADO = ('D', 'A', 'R')
	//ALQUILAR(A) RESERVAR(R) CANCELAR(D)
	NIVEL= (1..5)
FR

//INCREMENTAR LOS CAMPOS ALQUILADO
DUEÑOS=REGISTRO
	NDTO:N(6)
	DUEÑO:AN(20)
	NOMBRE:AN(20)
	ALQUILADOS:(4)
	RESERVAS: N(4)
	CACELADOS:(4)
FR
DEPTO:ARCHIVO DE DEPTO INDEXADO POR NRODEPTO
DUE:ARCHIVO DE DUEÑOS INDEXADO POR NDTO

transaccion_A:N(5)
J:N(67)
R: DPTOS
D: DUEÑOS
USER:N(4)
USER2: AM(20)
NIVELES, NO_NIVELES:ARRAY[1..5]


PROCEDIMIENTO IMPRIMIR_TRANSACIONES() ES
	PARA i:=1 a 5 HACER
		W("PARA EL NIVEL", i, " SE TIENEN LAS SIGUIENTES TRANSACIONES EXITOSAS:", NIVELES[i], " Y NO EXISTOSAS:", NO_NIVELES[i]);
		J:=J+NIVELES[i]
	FP
	W("EL PORCENTAJE DE TRANSACCIONES QUE CAMBIARON A ALQUILADO, SOBRE TRANSACIONES TOTALES EXITOSAS ES DE: " (transaccion_A/J)*100, "%")
FP

PROCEDIMIENTO NIVEL(X:ARRAY[1..5], Y:(1..5)) ES
	X[Y]:=X[Y]+1
FP

PROCEDIMIENTO ALQUILAR() ES 
	DEPTO.ESTADO:='A'
	GRABAR(DEPTO, R)
	DUE.ALQUILADOS:=DUE.ALQUILADOS+1
	GRABAR(DUE, D)
	NIVEL(NIVELES, DEPTO.NIVEL)
	transaccion_A:=transaccion_A+1
FP 

PROCEDIMIENTO RESERVAR() ES
	SI DEPTO.NIVEL > 3 ENTONCES
		DEPTO.ESTADO:= 'R'
		DUE.RESERVAS:=DUE.RESERVAS+1
		GRABAR(DEPTO, R)
		NIVEL(NIVELES, DEPTO.NIVEL)
	FIN SI
	NIVEL()
FR

PROCEDIMIENTO CANCELAR() ES
	DEPTO.ESTADO:= 'D'
	SI DUE.CANCELADO > 50 ENTONCES
		DEPTO.NIVEL=DEPTO.NIVEL-2
		SI DEPTO.NIVEL < 0 ENTONCES
			DEPTO.NIVEL:=1
		FIN SI
		GRABAR(DEPTO, R)
		DUE.CANCELADO:=DUE.CANCELADOS+1
		GRABAR(DUE, D)
		NIVEL(NIVELES, DEPTO.NIVEL)
	FIN SI 
FP 

PROCESO
ABRIR E/S(DUE), ABRIR E/S(DEPTO)
W("POR FAVOR INGRESE NRO DE DEPTO PARA ACRUALIZARLO"); R(USER)
MIENTRAS USER > 0 HACER
	DEPTO.NDTO:= USER; R(DEPTO, R)
	DUE.NRODEPTO:=USER; R(DUE, D)
	SI EXISTE ENTONCES 
		SEGUN DEPTO.ESTADO HACER
			='R' O 'A':ALQUILAR()
			='D':RESERVAR()
			='D' O 'R':CANCELAR()
			=OTRO W("ERROR ESTADO NO VALIDO"); NIVELES(NO_NIVELES, DEPTO.NIVEL)
		FS
	SINO 
		W("ERROR NO EXISTE NRO DE DEPTO DESEA DARLO DE ALTA? S/N")
		R(USER2)
		SI USER2 = 'S' ENTONCES 
			W("INGRESE LA INFORMACION DE DEPTO")
			NDTO:=USER
			W("INGRESE ESATDO")
			DEPTO.ESATDO:=USER2
			W("ENGRESE DESCRIPCION")
			DEPTO.DESCRIPCION:=USER2
			//ETC ECT LO MISMO CON DUEÑO
			GRABA(DUE, D)
			NIVEL(NIVELES, DEPTO.NIVEL)
			GRABAR(DEPTO, R)
			W("ACTUALIZADO CON EXITO")
		SINO 
			NIVEL(NO_NIVELES)
		FIN SINO
	FS
	W("POR FAVOR INGRESE OTRO NUMERO PARA ACTUALIZAR O INSERTAR, SI DESEA SALIR PRESIONE 0")
	R(USER)
FIN MIENTRAS
IMPRIMIR_TRANSACIONES()
FIN ALGORITMO

//Me llevo 45 minutos :D