ALGORITMO QATAR2022 ES
AMBIENTE
PROCEDIMIENTO TIPO_RESERVA() ES
	SEGUN Q HACER
		'E':: i:=1
		'P':: i:=2
		'Y':: i:=3
	FS
	A[i]:=A[i]+1
FP

PROCEDIMIENTO ACUMULAR_USER() ES 
	

PROCESO
ARR(SEC) AVZ(SEC, Q)
W("PORFAVOR, INGRESE ZONA A ANALIZAR Y ESTADIO"); R(ZONA), R(ESTADIO)
MIENTRAS NOFD(SEC) HACER
	MIENTRAS Q<>'%' HACER 
		RES_ESTADIO:=CONCATENAR(RES_ESTADIO, Q)
	FM 
	SI RES_ESTADIO=ESTADIO ENTONCES
		BANDERA1:=true
	FS
	REPETIR 
		AVZ(SEC, Q) 
	HASTA QUE Q='#'
	TIPO_RESERVA()
	REPETIR 
		AVZ(SEC, Q) 
	HASTA QUE Q='%'
	SI BANDERA1 Y Q=ZONA ENTONCES
		ACUMULAR_USER()
	FS
	CARGAR_RESERVAS()
FM

PARA i:=1 A 3 HACER 
	ESC("PARA EL TIPO RESERVA" i, "HAY", A[i] "RESERVAS")
FP 
SI RESERVAS_USUARIO=0 ENTONCES
	W("NO SE ENCONTRARON RESERVAS PARA ESTA ZONA O ESTADIO")
SINO
	W("CANTIDAD DE RESERVAS HECHAS EN EL ESTADIO", ESTADIO, " EN LA XONA", ZONA, "ES DE", RESERVAS_USUARIO)
	W("SECUECIa GENERADA CON EXITO")
FIN ACCION