ACCION EJERCICIO1 ES
AMBIENTE
CLIENTES=REGISTRO
	MES: N(2)
	CLIENTE:N(13)
	COD_TRAN: {'D', 'E', 'T'}
	MONEDA: {'P', 'U', 'E'}
	IMPORTE: REAL(13,2)
FR
MOVIM: ARCHIVO DE CLIENTES ORDENADO POR MES, CLIENTE Y COD_TRAN
R: CLIENTE

NODO=REGISTRO
	DATO:DATO_REG
	PROX:PUNTERO A NODO
FR
PRIM, P Q A:PUNTERO A NODO

TR: ARRAY [1..3] DE ENTEROS

TOT_ANUAL, TOTAL_OPERADO, OPERACIONES, RES_MES, RES_OP, MAYOR, EXTRANJERA, TOT_EXTRACCIONES_MES: ENTERO(4)
MONTO: REAL(100,2)
BANDERA:BOOLEAN
DATO_REG=REGISTRO
		CLIENTE
		TOTAL_OPERADO
		CANT_OPERACIONES
		IAF
	FR
AUX_DATO:DATO_REG

PROCEDIMIENTO transaccion_mas_solictada() ES
	SEGUN R.COD_TRAN HACER
		:'D'::=TR[1]:=TR[1]+1
		:'E'::=TR[2]:=TR[2]+1
		:'T'::=TR[3]:=TR[3]+1
	FS
FP

PROCEDIMIENTO ACERO() ES
	para I:=1 a 3 hacer 
		TR[I]:=0
	FP
FP


PROCEDIMIENTO TRATAR_MES() ES
	W("TOTAL DE OPERACION EN EL MES FUERON DE TOT_EXTRACCIONES_MES")
	W("DONDE, TOTAL EXTRACCION SOBRE EL MES:", TOT_EXTRACCIONES_MES/A[2]*100, "%", "Y PROCENTAJE DE OPERACIONES EN MONEDA EXTRANJERA EN EL MES FUERON DE" TOT_EXTRACCIONES_MES/EXTRANJERA*100, "%")
	PARA I:=1 A 3 HACER
		SI MAYOR< TR[I] ENTONCES
			MAYOR:=TR[I]
			RES_OP:=I
		FS
	FP
	W("LA OPERACION MAS HECHA EN EL MES FUE:")
	SEGUN RES_OP HACER
		:1::= W("DEPOSITO")
		:2::=W("EXTRACCION")
		:3::=W("TRANSFERENCIA")
	FS
	TOT_ANUAL:=TOT_ANUAL+TOT_EXTRACCIONES_MES
	TOT_EXTRACCIONES_MES:=0
	EXTRANJERA:=0
	ACERO()
	RES_MES:=R.MES
FP

PROCEDIMIENTO CALCULAR_IAF() ES
	P:=PRIM
	MIENTRAS P<>NIL HACER
		*P.IAF:=*P.CANT_OPERACIONES x *P.TOTAL_OPERADO
		P:=P.PROX
	FM

FP
PROCEDIMIENTO ORDENAR_LISTA() ES
    SI (PRIM = NIL) ENTONCES
        ESC("La lista ya está ordenada o vacia")
    SINO
        BANDERA := Falso;
        // mientras existan intercambios
        MIENTRAS NO BANDERA HACER
            BANDERA :=true
            P:=PRIM
            // recorrer lista y comparando con el siguiente
            MIENTRAS (*P.prox <> NIL) HACER
                A := *P.prox
                // si el de la izquierda es mayor que el de la derecha, intercambio
                SI (*P.DATO.IAF < *A.DATO.IAF) ENTONCES
                    AUX_DATO:= *P.DATO
                    *P.DATO:= *A.DATO
                    *A.DATO:= AUX_DATO
					BANDERA:=false
                SINO SI P.DATO.IAF= A.DATO.IAF HACER
					SI P.DATO.CANT_OPERACIONES<=A.DATO.CANT_OPERACIONES ENTONCES
						AUX_DATO:= *P.DATO
                    	*P.DATO:= *A.DATO
                    	*A.DATO:= AUX_DATO
						BANDERA:=false
					FS
				FS
                P := *P.prox
            FM
        FM
    FS
FP 

PROCEDIMIENTO TRATAR_CLIENTE() ES
	NUEVO(Q)
	*Q.CLIENTE:=CLIENTE_ID
	*Q.TOTAL_OPERADO:=MONTO
	*Q.CANT_OPERACIONES:=OPERACIONES
	*Q.IAF:=0
	*Q.ANT:=NIL
	*Q.PROX:=NIL
	
	SI PRIM=nil ENTONCES 
		PRIM:=Q
		*Q.ANT:=PRIM
		*Q.PROX:=nil
	SINO
		MIENTRAS *P.CLIENTE_ID<>*Q.CLIENTE_ID Y P.PROX<>nil
			P:=PROX
		FM
		SI P*CLIENTE_ID=*Q.CLIENTE_ID ENTONCES
			*P.TOTAL_OPERADO:=*P.TOTAL_OPERADO+ *Q.TOTAL_OPERADO
			*P.CANT_OPERACIONES:=*P.CANT_OPERACIONES+*Q.CANT_OPERACIONES
			DISPONER(Q)
		SINO
			*P.PROX:=Q
			*Q.ANT:=P
			*Q.PROX:=nil
		FS
	FS
	DISPONER(Q)
	OPERACION:=0
	MONTO;=0
FP

PROCESO ES
ABRIR E/(MOVIM), LEER(MOVIM, R)  //PONER A CERO LOS CONTADORES :VVVVVVVV

MIENTRAS NOFDA(MOVIM) HACER
	TRATAR_CLIENTE()
	SI REG_MES<>R.MES ENTONCES
		CORTE_MES()
	FS
	transaccion_mas_solictada()
	SI R.MONEDA= 'E' O R.MONEDA='U' ENTONCES
		EXTRANJERA:=EXTRANJERA+1
		MONTO:=MONTO+ CONVERTIR_a_PESO(R.IMPORTE, R.MONEDA)
	SINO 
		MONTO:=MONTO+R.IMPORTE
	FS
	OPERACION:=OPERACION+1
	TOT_EXTRACCIONES_MES:=TOT_EXTRACCIONES_MES+1
	LEER(MOVIM, R)
FM
CORTE_MES()
CALCULAR_IAF()
ORDENAR_LISTA()

P:=PRIM
W("TOP 5 PEORES EJERCICIOS")
PARA J:=1 A 5 HACER 
	W(J, P.DATO_REG)
FP	
W("TOTAL ANUAL", TOT_ANUAL)
FIN PROCESO

	
	//sin poner a vcerp TODOS los contadores, y declarar los registros me llevo 1:15 :(


ACCION EJERCICIO2 es 

ALGORITMO Universidad_Rendimiento
AMBIENTE
    ALUMNO=REGISTRO
        FACULTAD [1..3]
        CARRERA [1..5]
        LEGAJO N(8)
        PROM REAL(2,1)
        APROB N(2)
        REPROB N(2)
        CONDICION {'R', 'L'}
    FR

    ESTADISTICA=REGISTRO
        TOTAL_ALU N(3)
        REGULARES:N(2)
        SUM_PROM:REAL(3,1)
        MALASOS:N(2)
        ENRIESGO:N(2)
        MPROM:REAL
        MLEG:N(8)
        PPROM:REAL
        PLEG:N(8)
    FR

    ARCH: ARCHIVO DE ALUMNO
    R: ALUMNO

    M: ARREGLO [1..3, 1..5] DE ESTADISTICA
    
    f, c, I, J: N(1)
    PORCENTAJES_MALOS, MEJOR_FACU, MEJOR_PROM, AUX_SUMA_PROMEDIO:N(123)

PROCEDIMIENTO ACERO() ES
	PARA f := 1 HASTA 3 HACER
        PARA c := 1 HASTA 5 HACER
            M[f,c].TOTAL_ALU:=0
            M[f,c].REGULARES:=0
            M[f,c].SUM_PROM:=0
            M[f,c].MALASOS:=0
            M[f,c].ENRIESGO:=0
            M[f,c].MPROM:=-1
            M[f,c].PPROM:=11 
			//M[] LEGAJO BLA BLA
        FP
	FP
	MEJOR_FACU:=0
	MEJOR_PROM:=0
	AUX_SUMA_PROMEDIO:=0
	PORCENTAJES_MALOS:=0
FP

FUNCION RIESGOA(X, Y: NUMERICO(2))BOOLEAN
	SI X<Y ENTONCES
		SI R.PROM<6 ENTONCES
			RIESGOA:=true
		FS
	SINO 
		RIESGOA:=false
	FS
FF

PROCEDIMIENTO MEJOR_FACU() ES
	PARA f:1 a 3 HACER
		PARA C:=1 A 5 HACER
			AUX_SUMA_PROMEDIO:=M[F,C].SUM_PROM/M[F,C].TOTAL_ALU
			SI MEJOR_PROM< AUX_SUMA_PROMEDIO ENTONCES
				MEJOR_PROM:=AUX_SUMA_PROMEDIO
				I:=f
			FS
		FP
	FP
	W("LA FACULTAD CON MEJOR PROMEDIO ES", I, "CON UN PROMEDIO GENERAL DE", MEJOR_PROM)
FP

PROCESO
ACERO(), ABRIR E/(ARCH), LEER(ARCH, R)

MIENTRAS NFDA(ARCH)HACER
	f:=	R.FACULTAD
	c:=R.CARRERA
	SI R.CONDICION:='R' ENTONCES
		M[F,C].REGULARES:=M[F,C].REGULARES+1
	FS
	SI R.PROM< M[F,C].PPROM ENTONCES
		M[F,C].PPROM:=R.PROM
		M[F,C].PLEG:=R.LEGAJO
	SINO 
		SI R.PROM>M[F,C].MPROM ENTONCES
			M[F,C].MPROM:=R.PROM
			M[F,C].MLEG:=R.LEGAJO
		FS
	FS
	M[F,C].SUM_PROM:=M[F,C].SUM_PROM+R.PROM
	SI RIESGOA(R.APROB,RPROB) ENTONCES	
		M[F,C].ENRIESGO:=M[F,C].ENRIESGO+1
	SINO 
		SI SI R.APROB<R.REPROB ENTONCES
			M[F,C].MALASOS:=M[F,C].MALASOS+1
		FS
	FS
	M[F,C].TOTAL_ALU:=M[F,C].TOTAL_ALU+1
	LEER(ARCH,R)
FIN PROCESO
PARA f:=1 a 3 HACER
	PARA C:=1 A 5 HACER
		W("PARA LA CARRERA" C, "PROCETAJE DE REGULARES", (M[F,C].REGULARES/M[F,C].TOTAL_ALU)*100)
		W("MEJOR PROMEDIO PARA LA CARRERARA", C, "ES", M[F,C].MLEG, "CON PROMEDIO", M[F,C].MPROM)
		W("PEOR PROMEDIO PARA LA CARRERA", C, "ES" M[F,C].PLEG, "CON PROMEDIO", M[F,C].PPROM)
		W("CANTIDAD DE ALUMNOS EN RIESGO PARA CARRERA",C, "FACULTAD",F, "ES DE", M[F,C].ENRIESGO)
		PORCENTAJES_MALOS:=(M[F,C].MALASOS/M[F,C].TOTAL_ALU)*100
		SI PORCENTAJES_MALOS>30 ENTONCES
			W("MUCHOS MALASOS EN LA FACULTAD", F, "EN LA CARRERA DE IQ", C)
		FS
	FP
FP
MEJOR_FACU()
CERRAR(ARCH)
FINPROCESO