ACCION EJERCICIO2 es 

ALGORITMO Universidad_Rendimiento
AMBIENTE
    ALUMNO=REGISTRO
        FACULTAD [1..3]
        CARRERA [1..5]
        LEGAJO N(8)
        PROM REAL(2,1)
        APROB N(2)
        REPROB N(2)
        CONDICION {'R', 'L'}
    FR

    ESTADISTICA=REGISTRO
        TOTAL_ALU N(3)
        REGULARES:N(2)
        SUM_PROM:REAL(3,1)
        MALASOS:N(2)
        ENRIESGO:N(2)
        MPROM:REAL
        MLEG:N(8)
        PPROM:REAL
        PLEG:N(8)
    FR

    ARCH: ARCHIVO DE ALUMNO
    R: ALUMNO

    M: ARREGLO [1..3, 1..5] DE ESTADISTICA
    
    f, c, I, J: N(1)
    PORCENTAJES_MALOS, MEJOR_FACU, MEJOR_PROM, AUX_SUMA_PROMEDIO:N(123)

PROCEDIMIENTO ACERO() ES
	PARA f := 1 HASTA 3 HACER
        PARA c := 1 HASTA 5 HACER
            M[f,c].TOTAL_ALU:=0
            M[f,c].REGULARES:=0
            M[f,c].SUM_PROM:=0
            M[f,c].MALASOS:=0
            M[f,c].ENRIESGO:=0
            M[f,c].MPROM:=-1
            M[f,c].PPROM:=11 
			//M[] LEGAJO BLA BLA
        FP
	FP
	MEJOR_FACU:=0
	MEJOR_PROM:=0
	AUX_SUMA_PROMEDIO:=0
	PORCENTAJES_MALOS:=0
FP

FUNCION RIESGOA(X, Y: NUMERICO(2))BOOLEAN
	SI X<Y ENTONCES
		SI R.PROM<6 ENTONCES
			RIESGOA:=true
		FS
	SINO 
		RIESGOA:=false
	FS
FF

PROCEDIMIENTO MEJOR_FACU() ES
	PARA f:1 a 3 HACER
		PARA C:=1 A 5 HACER
			AUX_SUMA_PROMEDIO:=M[F,C].SUM_PROM/M[F,C].TOTAL_ALU
			SI MEJOR_PROM< AUX_SUMA_PROMEDIO ENTONCES
				MEJOR_PROM:=AUX_SUMA_PROMEDIO
				I:=f
			FS
		FP
	FP
	W("LA FACULTAD CON MEJOR PROMEDIO ES", I, "CON UN PROMEDIO GENERAL DE", MEJOR_PROM)
FP

PROCESO
ACERO(), ABRIR E/(ARCH), LEER(ARCH, R)

MIENTRAS NFDA(ARCH)HACER
	f:=	R.FACULTAD
	c:=R.CARRERA
	SI R.CONDICION:='R' ENTONCES
		M[F,C].REGULARES:=M[F,C].REGULARES+1
	FS
	SI R.PROM< M[F,C].PPROM ENTONCES
		M[F,C].PPROM:=R.PROM
		M[F,C].PLEG:=R.LEGAJO
	SINO 
		SI R.PROM>M[F,C].MPROM ENTONCES
			M[F,C].MPROM:=R.PROM
			M[F,C].MLEG:=R.LEGAJO
		FS
	FS
	M[F,C].SUM_PROM:=M[F,C].SUM_PROM+R.PROM
	SI RIESGOA(R.APROB,RPROB) ENTONCES	
		M[F,C].ENRIESGO:=M[F,C].ENRIESGO+1
	SINO 
		SI SI R.APROB<R.REPROB ENTONCES
			M[F,C].MALASOS:=M[F,C].MALASOS+1
		FS
	FS
	M[F,C].TOTAL_ALU:=M[F,C].TOTAL_ALU+1
	LEER(ARCH,R)
FIN PROCESO
PARA f:=1 a 3 HACER
	PARA C:=1 A 5 HACER
		W("PARA LA CARRERA" C, "PROCETAJE DE REGULARES", (M[F,C].REGULARES/M[F,C].TOTAL_ALU)*100)
		W("MEJOR PROMEDIO PARA LA CARRERARA", C, "ES", M[F,C].MLEG, "CON PROMEDIO", M[F,C].MPROM)
		W("PEOR PROMEDIO PARA LA CARRERA", C, "ES" M[F,C].PLEG, "CON PROMEDIO", M[F,C].PPROM)
		W("CANTIDAD DE ALUMNOS EN RIESGO PARA CARRERA",C, "FACULTAD",F, "ES DE", M[F,C].ENRIESGO)
		PORCENTAJES_MALOS:=(M[F,C].MALASOS/M[F,C].TOTAL_ALU)*100
		SI PORCENTAJES_MALOS>30 ENTONCES
			W("MUCHOS MALASOS EN LA FACULTAD", F, "EN LA CARRERA DE IQ", C)
		FS
	FP
FP
MEJOR_FACU()
CERRAR(ARCH)
FINPROCESO